title: EE 194/290C Lab Tutorials
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Course Website: https://ucb-ee290c.github.io/
