title: EE 194/290C Tutorials
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

color_scheme: dark

url: https://ucb-ee290c.github.io/tutorials

search_enabled: true
heading_anchors: true

aux_links:
  Course Website: https://ucb-ee290c.github.io/

callouts:
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
