#!/usr/bin/env python3
"""Regenerate the `weeks:` block of a semester's data file from the calendar
spreadsheet.

Usage:
    python scripts/import_calendar.py "EE194_290 Bringup Fa26 Semester Calendar.xlsx"
    python scripts/import_calendar.py <xlsx> --semester fa26

The [Public] sheet is the source of truth. Its columns are:

    #  Date  Topic  Slides  Lab Assignments  Team Milestones  Extra Notes

Cells may hold several entries separated by newlines; each becomes one list
item. Only the `weeks:` block is rewritten -- everything else in the data
file (course details, staff, slide_links, sections, nav) is left untouched,
so it is safe to re-run after editing the sheet.

A date that is not a Friday in the expected year is written as TBD rather
than published wrong; the script reports every one it skipped.

Requires: openpyxl
"""

import argparse
import datetime
import io
import os
import re
import sys

try:
    import openpyxl
except ImportError:  # pragma: no cover
    sys.exit("openpyxl is required:  pip install openpyxl")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANNER = "# " + "-" * 75 + "\n"

HEADER = BANNER + """# Weekly schedule, generated by scripts/import_calendar.py from the [Public]
# sheet of the semester calendar spreadsheet.
#
# Class meets Fridays; `date` is that Friday and `start` is the Monday of the
# same week, which is what marks the current row in the rendered calendar.
#
# Edit the spreadsheet and re-import rather than hand-editing this block.
# Add a `url:` to any entry to turn it into a link; slide deck URLs belong in
# `slide_links` above, which the importer does not touch.
#
# `milestones` comes from the sheet's Team Milestones column but is not
# rendered: that column was removed from the calendar table. It is kept here
# so the column can be restored without re-importing.
""" + BANNER + "weeks:\n"


def cell(ws, row, col):
    value = ws.cell(row, col).value
    return "" if value is None else str(value).strip()


def entries(raw, strip_ext=False):
    """Split a multi-line cell into individual items.

    strip_ext drops a trailing file extension, so the sheet's "Lecture 1.pptx"
    reads as "Lecture 1" on the site. That cleaned name is also the key used
    to look the item up in `slide_links`.
    """
    items = [p.strip() for p in re.split(r"[\r\n]+", raw) if p.strip()]
    if strip_ext:
        items = [re.sub(r"\.(pptx?|pdf|key|odp)$", "", i, flags=re.I) for i in items]
    return items


def esc(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def yaml_list(key, items, indent="    "):
    if not items:
        return ""
    lines = ["%s%s:" % (indent, key)]
    lines += ['%s  - name: "%s"' % (indent, esc(i)) for i in items]
    return "\n".join(lines) + "\n"


def build(ws, year):
    blocks, skipped = [], []

    for row in range(2, ws.max_row + 1):
        label = cell(ws, row, 1)
        if not label:
            continue
        match = re.search(r"(\d+)", label)
        if not match:
            continue
        number = int(match.group(1))

        raw_date = ws.cell(row, 2).value
        friday = None
        if isinstance(raw_date, datetime.datetime):
            d = raw_date.date()
            if d.year == year and d.weekday() == 4:
                friday = d
            else:
                skipped.append((label, d))

        out = ["  - number: %d" % number]
        if friday:
            monday = friday - datetime.timedelta(days=4)
            out.append('    date: "%s %d"' % (friday.strftime("%b"), friday.day))
            out.append('    start: "%s"' % monday.isoformat())
        else:
            out.append('    date: "TBD"')
            out.append(
                "    # Spreadsheet has %s for this row -- not a %d Friday."
                % (
                    raw_date.date() if isinstance(raw_date, datetime.datetime)
                    else raw_date or "no date",
                    year,
                )
            )
        out.append('    topic: "%s"' % esc(cell(ws, row, 3)))

        block = "\n".join(out) + "\n"
        block += yaml_list("slides", entries(cell(ws, row, 4), strip_ext=True))
        block += yaml_list("labs", entries(cell(ws, row, 5)))
        block += yaml_list("milestones", entries(cell(ws, row, 6)))

        note = cell(ws, row, 7)
        if note:
            block += '    notes: "%s"\n' % esc(note)

        blocks.append(block)

    return blocks, skipped


def splice(path, weeks_yaml):
    """Replace just the weeks block, between its banner and the next one."""
    src = io.open(path, encoding="utf-8").read()
    start = src.index(BANNER + "# Weekly schedule")
    # Search for the closing banner from past the `weeks:` line: the header
    # written above ends with a banner of its own, and anchoring on that
    # would replace only the comment and duplicate the data.
    weeks_at = src.index("\nweeks:\n", start)
    end = src.index(BANNER, weeks_at)
    io.open(path, "w", encoding="utf-8", newline="\n").write(
        src[:start] + weeks_yaml + "\n" + src[end:]
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("xlsx", help="path to the semester calendar spreadsheet")
    ap.add_argument("--semester", default="fa26",
                    help="data file key under _data/ (default: fa26)")
    ap.add_argument("--sheet", default="Public", help="sheet name (default: Public)")
    ap.add_argument("--year", type=int, default=2026,
                    help="expected year for the Friday dates (default: 2026)")
    args = ap.parse_args()

    data_file = os.path.join(REPO, "_data", "%s.yml" % args.semester)
    if not os.path.exists(data_file):
        sys.exit("no such data file: %s" % data_file)

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    if args.sheet not in wb.sheetnames:
        sys.exit("sheet %r not found; available: %s" % (args.sheet, wb.sheetnames))

    blocks, skipped = build(wb[args.sheet], args.year)
    if not blocks:
        sys.exit("no week rows found on sheet %r" % args.sheet)

    splice(data_file, HEADER + "\n".join(blocks))

    print("imported %d weeks into %s" % (len(blocks), os.path.relpath(data_file, REPO)))
    for label, d in skipped:
        print("  DATE NOT IMPORTED  %s -> %s (not a %d Friday)" % (label, d, args.year))
    return 0


if __name__ == "__main__":
    sys.exit(main())
