#!/usr/bin/env python3
"""Regenerate the `weeks:` block of a semester data file from the calendar
spreadsheet.

    python scripts/import_calendar.py "Fa26 Semester Calendar.xlsx"
    python scripts/import_calendar.py <xlsx> --semester fa26

The [Public] sheet is the source of truth, with columns:

    #  Date  Topic  Slides  Lab Assignments  Team Milestones  Extra Notes

Multi-line cells become multiple list items. Only the `weeks:` block is
rewritten, so hand-maintained content elsewhere in the file survives and the
script is safe to re-run.

Requires: openpyxl
"""

import argparse
import datetime
import io
import os
import re
import sys

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required:  pip install openpyxl")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANNER = "# " + "-" * 75 + "\n"

HEADER = BANNER + """# Weekly schedule, generated by scripts/import_calendar.py from the [Public]
# sheet of the semester calendar spreadsheet.
#
# Class meets Fridays; `date` is that Friday and `start` is the Monday of the
# same week, which marks the current row in the rendered calendar.
#
# Edit the spreadsheet and re-import rather than editing this block by hand.
# Slide deck URLs belong in `slide_links` above, which the importer leaves
# alone. `milestones` is imported but not rendered.
""" + BANNER + "weeks:\n"


def cell(ws, row, col):
    value = ws.cell(row, col).value
    return "" if value is None else str(value).strip()


def entries(raw, strip_ext=False):
    items = [p.strip() for p in re.split(r"[\r\n]+", raw) if p.strip()]
    if strip_ext:
        # The trimmed name is also the key used to look a deck up in
        # `slide_links`, so "Lecture 1.pptx" must become "Lecture 1".
        items = [re.sub(r"\.(pptx?|pdf|key|odp)$", "", i, flags=re.I) for i in items]
    return items


def esc(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def yaml_list(key, items, indent="    "):
    if not items:
        return ""
    lines = ["%s%s:" % (indent, key)]
    lines += ['%s  - name: "%s"' % (indent, esc(i)) for i in items]
    return "\n".join(lines) + "\n"


def build(ws, year):
    blocks, skipped = [], []

    for row in range(2, ws.max_row + 1):
        label = cell(ws, row, 1)
        match = re.search(r"(\d+)", label) if label else None
        if not match:
            continue
        number = int(match.group(1))

        raw_date = ws.cell(row, 2).value
        friday = None
        if isinstance(raw_date, datetime.datetime):
            date = raw_date.date()
            if date.year == year and date.weekday() == 4:
                friday = date
            else:
                skipped.append((label, date))

        out = ["  - number: %d" % number]
        if friday:
            out.append('    date: "%s %d"' % (friday.strftime("%b"), friday.day))
            out.append('    start: "%s"'
                       % (friday - datetime.timedelta(days=4)).isoformat())
        else:
            out.append('    date: "TBD"')
        out.append('    topic: "%s"' % esc(cell(ws, row, 3)))

        block = "\n".join(out) + "\n"
        block += yaml_list("slides", entries(cell(ws, row, 4), strip_ext=True))
        block += yaml_list("labs", entries(cell(ws, row, 5)))
        block += yaml_list("milestones", entries(cell(ws, row, 6)))

        note = cell(ws, row, 7)
        if note:
            block += '    notes: "%s"\n' % esc(note)

        blocks.append(block)

    return blocks, skipped


def splice(path, weeks_yaml):
    src = io.open(path, encoding="utf-8").read()
    start = src.index(BANNER + "# Weekly schedule")
    # Look for the closing banner from past the `weeks:` line: HEADER ends
    # with a banner of its own, and anchoring on that would replace only the
    # comment and leave a duplicate copy of the data behind.
    end = src.index(BANNER, src.index("\nweeks:\n", start))
    io.open(path, "w", encoding="utf-8", newline="\n").write(
        src[:start] + weeks_yaml + "\n" + src[end:]
    )


def report(blocks, skipped, year):
    weeks_by_start = {}
    for block in blocks:
        number = re.search(r"number: (\d+)", block).group(1)
        start = re.search(r'start: "([\d-]+)"', block)
        if start:
            weeks_by_start.setdefault(start.group(1), []).append(number)

    for start, numbers in sorted(weeks_by_start.items()):
        if len(numbers) > 1:
            print("  WARNING  weeks %s share the week of %s"
                  % (" and ".join(numbers), start))
    for label, date in skipped:
        print("  DATE NOT IMPORTED  %s -> %s (not a %d Friday)" % (label, date, year))


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("xlsx", help="path to the semester calendar spreadsheet")
    parser.add_argument("--semester", default="fa26", help="data file key under _data/")
    parser.add_argument("--sheet", default="Public", help="sheet name")
    parser.add_argument("--year", type=int, default=2026,
                        help="expected year for the Friday dates")
    args = parser.parse_args()

    data_file = os.path.join(REPO, "_data", "%s.yml" % args.semester)
    if not os.path.exists(data_file):
        sys.exit("no such data file: %s" % data_file)

    workbook = openpyxl.load_workbook(args.xlsx, data_only=True)
    if args.sheet not in workbook.sheetnames:
        sys.exit("sheet %r not found; available: %s"
                 % (args.sheet, workbook.sheetnames))

    blocks, skipped = build(workbook[args.sheet], args.year)
    if not blocks:
        sys.exit("no week rows found on sheet %r" % args.sheet)

    splice(data_file, HEADER + "\n".join(blocks))
    print("imported %d weeks into %s"
          % (len(blocks), os.path.relpath(data_file, REPO)))
    report(blocks, skipped, args.year)
    return 0


if __name__ == "__main__":
    sys.exit(main())
